### ISSUE TITLE
`spacelift_module`: `labels` is not validating for sets

### ISSUE THREAD

**Issue by Maelstromeous** [spacelift-io/terraform-provider-spacelift#523]
Currently you are able to create a resource but it unknowingly omits labels as a user may be able to supply `labels` a set.

e.g.:
```hcl
resource "spacelift_module" "this" {
  name       = "x"
  branch     = "x"
  repository = "x"
  labels     = { "foo": "bar" }
}
```
Results in the below, where labels is being silently ignored:
```
  #spacelift_module.this will be created
  + resource "spacelift_module" "this" {
      + branch                           = "x"
      + id                               = (known after apply)
      + name                             = "services-template"
      + project_root                     = "x"
    }
```

Ideally, validation should be added in the provider to demand a set, not a map.

**Comment by marcinwyszynski** [comment]
This looks like a Terraform/OpenTofu or HCL bug rather than provider. The provider correctly specifies the type of the input as `schema.TypeSet`, so it should not be performing any further type-checking. As such, the provider is working as intended. It's Terraform that should alert the author that they're violating the provider schema.

Please file this against as a bug against Terraform/OpenTofu.
