### ISSUE TITLE
spacelift_worker private_key returns null

### ISSUE THREAD

**Issue by oh-nathaniel-bobrick** [spacelift-io/terraform-provider-spacelift#526]
The [spacelift_worker_pool private_key](https://registry.terraform.io/providers/spacelift-io/spacelift/latest/docs/resources/worker_pool#private_key) attribute returns a null value. 

Spacelift provider: 1.10.0
Hashicorp/tls provider: 4.0.5
Terraform: 1.5.7

```hcl
resource "tls_private_key" "this" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "tls_cert_request" "this" {
  private_key_pem = tls_private_key.this.private_key_pem

  subject {
    organization = "some-company"
  }
}

resource "spacelift_worker_pool" "this" {
  name        = "worker"
  csr         = base64encode(tls_cert_request.this.cert_request_pem)
  space_id    = data.spacelift_space.root.id
}

output "this" {
  value = {
    private_key = nonsensitive(spacelift_worker_pool.this.private_key)
  }
}
```

```
Changes to Outputs:
  + this = {
      + private_key = null
    }
```

**Comment by marcinwyszynski** [comment]
Correct, this is by design. The private key field would only be filled out if you didn't specify the CSR. That would have the provider generate a key for you. But we have no way of generating a private key from a CSR.

[Here](https://github.com/spacelift-io/terraform-provider-spacelift/blob/main/spacelift/resource_worker_pool.go#L116-L157) is the relevant piece of code.
